services:
  - type: web
    name: workshop-springboot3-jpa
    env: java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/course-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: JAVA_VERSION
        value: 21